import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/AppHeader";
import Footer from "@/components/AppFooter";
import QCProvider, { ChartJSProvider } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-50 min-h-screen flex flex-col w-full">
          <Header />
          <QCProvider>
            <ChartJSProvider>
              <main className="flex-1 max-w-7xl mx-auto px-4 py-8 w-full">
                {children}
              </main>
            </ChartJSProvider>
          </QCProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
