name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: create credentials file
      run:
        echo '${{ secrets.env_file }}' > .env
    - name: Build and run
      run: |
        docker build . --tag swe-lab-fr
        docker stop frontend || true
        docker rm frontend || true
        docker run -d --name frontend -p 3000:3000 --env-file .env swe-lab-fr